library(datasets)
data(iris)
View(iris)
barplot(table(iris$Petal.Width), main = "Petal Width", col = "gray35")
barplot(table(iris$Petal.Length), main = "Petal lenght", col = "gray35")
barplot(table(iris$Sepal.Length), main = "Sepal Length", col = "gray35")
barplot(table(iris$Sepal.Width), main = "Sepal width", col = "gray35")
boxplot(iris)
hist(iris$Petal.Length)
hist(iris$Petal.Width)
hist(iris$Sepal.Length)
hist(iris$Sepal.Width)
plot(density(iris$Petal.Length))
plot(density(iris$Petal.Width))
plot(density(iris$Sepal.Length))
plot(density(iris$Petal.Width))
barplot(table(iris$Species=="setosa",iris$Petal.Length))
barplot(table(iris$Species=="setosa",iris$Petal.Width))
barplot(table(iris$Species=="setosa",iris$Sepal.Length))
barplot(table(iris$Species=="setosa",iris$Sepal.Width))
barplot(table(iris$Species=="versicolor",iris$Petal.Length))
barplot(table(iris$Species=="versicolor",iris$Petal.Width))
barplot(table(iris$Species=="versicolor",iris$Sepal.Length))
barplot(table(iris$Species=="versicolor",iris$Sepal.Width))
barplot(table(iris$Species=="virginica",iris$Petal.Length))
barplot(table(iris$Species=="virginica",iris$Petal.Width))
barplot(table(iris$Species=="virginica",iris$Sepal.Length))
barplot(table(iris$Species=="virginica",iris$Sepal.Width))
summary(iris)
x<-iris$Sepal.Length
y<-iris$Petal.Width
cor(x,y,use = "complete.obs",method = "pearson")
x<-iris$Sepal.Length
y<-iris$Petal.Width
t.test(x, y, alternative = c("less"), 
       paired = FALSE, var.equal = FALSE, conf.level = 0.95)
x=iris[,-5]
y=iris$Species
km <- kmeans(x,3)
km
table(y,km$cluster)
plot(x[c("Sepal.Length", "Sepal.Width")], col=km$cluster)
points(km$centers[,c("Sepal.Length", "Sepal.Width")], col=1:3, pch=23, cex=3)
plot(x[c("Petal.Length", "Petal.Width")], col=km$cluster)
points(km$centers[,c("Petal.Length", "Petal.Width")], col=1:3, pch=23, cex=3)
plot(x[c("Sepal.Length", "Petal.Width")], col=km$cluster)
points(km$centers[,c("Sepal.Length", "Petal.Width")], col=1:3, pch=23, cex=3)
plot(x[c("Sepal.Width", "Petal.Length")], col=km$cluster)
points(km$centers[,c("Sepal.Width", "Petal.Length")], col=1:3, pch=23, cex=3)
